spring:
  profiles:
    active: mongo, gemini, mysql, prompt

---

logging:
  # 로그 파일 설정
  file:
    # dockerfile 부분에 만들어 놓음
    name: /app/logs/spring-batch.log
  pattern:
    # 파일에 저장될 로그 패턴
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    # 콘솔에 출력될 로그 패턴
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  
  level:
    # Spring 관련 로그
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org.springframework.data.mongodb: DEBUG  # MongoDB 쿼리 로그 보기
    org.springframework.batch: INFO
    
    # 패키지별 로거 설정
    HeoJin.SpringBatch.job: DEBUG           # Job 관련 로그
    HeoJin.SpringBatch.config: INFO         # 설정 관련 로그
    HeoJin.SpringBatch.entity: WARN         # Entity 관련 로그
    HeoJin.SpringBatch.job.recipeItemReader: DEBUG      # Reader 로그
    HeoJin.SpringBatch.job.recipeItemProcessor: DEBUG   # Processor 로그
    HeoJin.SpringBatch.job.recipeItemWriter: DEBUG      # Writer 로그
    HeoJin.SpringBatch.job.recipeListener: INFO         # Listener 로그
    
    # 기본 로그 레벨
    root: INFO


---
spring:
  batch:
    job:
#      enabled: false # 자동 실행 X
      name: processDataJob
#      name: testMongoJob
#      # 명령어나 launcher 같은 거 이용할듯
    jdbc:
      initialize-schema: always # 메타 데이터 테이블


---
spring:

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect





