spring:
  profiles:
    active: mongo, gemini, mysql, prompt

---

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org.springframework.data.mongodb: DEBUG  # MongoDB 쿼리 로그 보기
    root: INFO


---
spring:
  batch:
    job:
#      enabled: false # 자동 실행 X
      name: processDataJob
#      name: testMongoJob
#      # 명령어나 launcher 같은 거 이용할듯
    jdbc:
      initialize-schema: always # 메타 데이터 테이블


---
spring:

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect





