spring:
  profiles:
    active: mongo, gemini, mysql

---
spring:
  config:
    activate:
      on-profile: mongo, gemini, mysql
logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org.springframework.data.mongodb: DEBUG  # MongoDB 쿼리 로그 보기
    root: INFO


---
spring:
  batch:
    jdbc:
      initialize-schema: always # 메타 데이터 테이블
      schema: classpath:org/springframework/batch/core/schema-@@platform@@.sql
