spring:
  profiles:
    active: mongo, gemini, prompt
    ## docker 가 우선순위가 높음
    ## 덮어써서 그런듯

---

logging:
  # 로그 파일 설정
  file:
    # dockerfile 부분에 만들어 놓음
    # docker container 가 먼저 시작될듯
    name: /app/logs/spring-batch.log
  pattern:
    # 파일에 저장될 로그 패턴
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    # 콘솔에 출력될 로그 패턴
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  
#  level:
#    # 기본 로그 레벨
#    ## warn 이랑 eroor 만 기록됨
#    root: WARN


---
spring:
  batch:
    job:
#      enabled: false # 자동 실행 X
      name: dummyDataJob3
#      name: testMongoJob
#      # 명령어나 launcher 같은 거 이용할듯
    jdbc:
      initialize-schema: always # 메타 데이터 테이블


---
spring:

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect





